import { UserPermissions, UserRole } from '@/types';

export const getDefaultPermissions = (role: UserRole): UserPermissions => {
  switch (role) {
    case 'developer':
      return {
        viewDashboard: true,
        viewProjects: true,
        createProjects: true,
        editProjects: true,
        deleteProjects: true,
        viewTasks: true,
        createTasks: true,
        editTasks: true,
        deleteTasks: true,
        assignTasks: true,
        viewWorkflow: true,
        editWorkflow: true,
        viewStock: true,
        editStock: true,
        addStock: true,
        deleteStock: true,
        viewCalendar: true,
        viewEmployees: true,
        manageEmployees: true,
        viewFiles: true,
        uploadFiles: true,
        downloadFiles: true,
        deleteFiles: true,
        sendFiles: true,
        viewReports: true,
        createReports: true,
        viewSettings: true,
        managePermissions: true,
        viewAdminPanel: true,
        sendMessages: true,
        receiveMessages: true,
        viewNotifications: true,
      };
    case 'manager':
      return {
        viewDashboard: true,
        viewProjects: true,
        createProjects: true,
        editProjects: true,
        deleteProjects: false,
        viewTasks: true,
        createTasks: true,
        editTasks: true,
        deleteTasks: false,
        assignTasks: true,
        viewWorkflow: true,
        editWorkflow: true,
        viewStock: true,
        editStock: true,
        addStock: true,
        deleteStock: false,
        viewCalendar: true,
        viewEmployees: true,
        manageEmployees: false,
        viewFiles: true,
        uploadFiles: true,
        downloadFiles: true,
        deleteFiles: false,
        sendFiles: true,
        viewReports: true,
        createReports: true,
        viewSettings: true,
        managePermissions: false,
        viewAdminPanel: false,
        sendMessages: true,
        receiveMessages: true,
        viewNotifications: true,
      };
    case 'employee':
      return {
        viewDashboard: true,
        viewProjects: true,
        createProjects: false,
        editProjects: false,
        deleteProjects: false,
        viewTasks: true,
        createTasks: false,
        editTasks: false,
        deleteTasks: false,
        assignTasks: false,
        viewWorkflow: true,
        editWorkflow: false,
        viewStock: true,
        editStock: false,
        addStock: false,
        deleteStock: false,
        viewCalendar: true,
        viewEmployees: false,
        manageEmployees: false,
        viewFiles: true,
        uploadFiles: false,
        downloadFiles: true,
        deleteFiles: false,
        sendFiles: false,
        viewReports: false,
        createReports: true,
        viewSettings: true,
        managePermissions: false,
        viewAdminPanel: false,
        sendMessages: true,
        receiveMessages: true,
        viewNotifications: true,
      };
  }
};

export const permissionLabels: Record<keyof UserPermissions, { fr: string; ar: string; tn: string }> = {
  viewDashboard: { fr: 'Voir le tableau de bord', ar: 'عرض لوحة القيادة', tn: 'شوف الطابلو' },
  viewProjects: { fr: 'Voir les projets', ar: 'عرض المشاريع', tn: 'شوف المشاريع' },
  createProjects: { fr: 'Créer des projets', ar: 'إنشاء مشاريع', tn: 'زيد مشاريع' },
  editProjects: { fr: 'Modifier les projets', ar: 'تعديل المشاريع', tn: 'بدّل المشاريع' },
  deleteProjects: { fr: 'Supprimer les projets', ar: 'حذف المشاريع', tn: 'امسح المشاريع' },
  viewTasks: { fr: 'Voir les tâches', ar: 'عرض المهام', tn: 'شوف الخدمات' },
  createTasks: { fr: 'Créer des tâches', ar: 'إنشاء مهام', tn: 'زيد خدمات' },
  editTasks: { fr: 'Modifier les tâches', ar: 'تعديل المهام', tn: 'بدّل الخدمات' },
  deleteTasks: { fr: 'Supprimer les tâches', ar: 'حذف المهام', tn: 'امسح الخدمات' },
  assignTasks: { fr: 'Assigner des tâches', ar: 'تعيين مهام', tn: 'عطي خدمات' },
  viewWorkflow: { fr: 'Voir le flux de travail', ar: 'عرض سير العمل', tn: 'شوف الخدمة' },
  editWorkflow: { fr: 'Modifier le flux de travail', ar: 'تعديل سير العمل', tn: 'بدّل الخدمة' },
  viewStock: { fr: 'Voir le stock', ar: 'عرض المخزون', tn: 'شوف الماغازان' },
  editStock: { fr: 'Modifier le stock', ar: 'تعديل المخزون', tn: 'بدّل الماغازان' },
  addStock: { fr: 'Ajouter au stock', ar: 'إضافة للمخزون', tn: 'زيد للماغازان' },
  deleteStock: { fr: 'Supprimer du stock', ar: 'حذف من المخزون', tn: 'امسح من الماغازان' },
  viewCalendar: { fr: 'Voir le calendrier', ar: 'عرض التقويم', tn: 'شوف الكالندري' },
  viewEmployees: { fr: 'Voir les employés', ar: 'عرض الموظفين', tn: 'شوف الخدّامة' },
  manageEmployees: { fr: 'Gérer les employés', ar: 'إدارة الموظفين', tn: 'تصرف في الخدّامة' },
  viewFiles: { fr: 'Voir les fichiers', ar: 'عرض الملفات', tn: 'شوف الملفات' },
  uploadFiles: { fr: 'Télécharger des fichiers', ar: 'رفع الملفات', tn: 'طلّع ملفات' },
  downloadFiles: { fr: 'Télécharger des fichiers', ar: 'تحميل الملفات', tn: 'حط ملفات' },
  deleteFiles: { fr: 'Supprimer des fichiers', ar: 'حذف الملفات', tn: 'امسح ملفات' },
  sendFiles: { fr: 'Envoyer des fichiers', ar: 'إرسال الملفات', tn: 'ابعث ملفات' },
  viewReports: { fr: 'Voir les rapports', ar: 'عرض التقارير', tn: 'شوف التقارير' },
  createReports: { fr: 'Créer des rapports', ar: 'إنشاء تقارير', tn: 'زيد تقارير' },
  viewSettings: { fr: 'Voir les paramètres', ar: 'عرض الإعدادات', tn: 'شوف الإعدادات' },
  managePermissions: { fr: 'Gérer les permissions', ar: 'إدارة الصلاحيات', tn: 'تصرف في الصلاحيات' },
  viewAdminPanel: { fr: 'Voir le panneau admin', ar: 'عرض لوحة الإدارة', tn: 'شوف لوحة الأدمين' },
  sendMessages: { fr: 'Envoyer des messages', ar: 'إرسال رسائل', tn: 'ابعث رسائل' },
  receiveMessages: { fr: 'Recevoir des messages', ar: 'استقبال رسائل', tn: 'استقبل رسائل' },
  viewNotifications: { fr: 'Voir les notifications', ar: 'عرض الإشعارات', tn: 'شوف الإشعارات' },
};
